### ISSUE TITLE
App not able to handle large organizations

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/explorer#99]
When putting "ceph" as the search bar option, the app locks up. This much data our current structure is not able to handle. We need to determine our options to be able to populate graphs when there are queries with large amounts of data.

**Comment by cdolfi** [comment]
This error does not happen when working locally. The commit query/graph does give a "SyntaxError: Unexpected end of JSON input" error, but when given a little time it does populate. All other queries and graphs work as expected

**Comment by JamesKunstle** [comment]
For historic purposes, the solution to this problem was as follows:
At the time of this issue's creation, we were storing all of the data from our database queries in the client's browser session. This is obviously terrible design, our understanding of how Dash implemented caching was wrong.
We switched to caching user requests on the server-side and having a worker pool complete queries on a job queue.
